version: '3.8'
services:
  oracle-xe: # <.>
    environment:
      - ORACLE_PASSWORD=oracle
    image: gvenzl/oracle-xe:slim-faststart # <.>
    ports:
      - "1521:1521"
    restart: unless-stopped
    volumes:
      - oracle-volume:/opt/oracle/oradata # <.>

  oracle-sqlcl: # <.>
    image: container-registry.oracle.com/database/sqlcl:latest # <.>
    volumes:
      - ./sql_scripts:/opt/oracle/sql_scripts/
    stdin_open: true
    tty: true
    links:
      - oracle-xe:oracle-xe # <.>
volumes:
  oracle-volume: